[package]
name = "bomby"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy-inspector-egui = "0.14"
iyes_loopless = "0.9"
leafwing-input-manager = "0.7"
itertools = "0.10"
bevy_ninepatch = "0.9"
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk" }

[features]
dev = ["bevy/dynamic"]
 
[profile.dev.package."*"]
opt-level = 3
